Models/newUsers.cs
using System.ComponentModel.DataAnnotations;

namespace uTestAndForms.Models;

public class newUsers
{
    [Key] public int Id { get; set; }

    [Required] public string Name { get; set; }

    [Required] public string City { get; set; }

    [StringLength(12)] public string State { get; set; }
}

Pages/About/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace uTestAndForms.Pages.About;

public class Index : PageModel
{
    public void OnGet()
    {
        
    }
}

Pages/Blogs/Index.cshtml.cs
using DataAccessLibrary;
using DataAccessLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;

namespace uTestAndForms.Pages.Blogs;

public class IndexForBlogs : PageModel
{
    public IDataAccess _data;

    public ILogger<IndexForBlogs> _logger;

    public IEnumerable<newUsers> newUsers;


    public IndexForBlogs(IOptions<ConnectionStrings> cnStrings, IDataAccess data, ILogger<IndexForBlogs> Logger)
    {
        _logger = Logger;
        _data = data;
    }

    [BindProperty] public newUsers newUsersModel { get; set; } = new();


    [BindProperty(SupportsGet = true)] public string nameParam { get; set; }


    public async Task<IActionResult> OnGet()
    {
        var someData = await _data.ReadFromDB();

        if (!nameParam.IsNullOrEmpty())
        {
            _logger.LogInformation("loaded users");

            someData = someData.Where(d => d.Name.Contains(nameParam));
        }


        newUsers = someData;
        return Page();
    }

    public async Task<IActionResult> OnGetRefresh()
    {
        _logger.LogInformation("refreshed page");
        return Redirect("/Blogs");
    }

    public async Task<IActionResult> OnPostDeleteUserWithId()
    {
        await _data.DeleteUser(newUsersModel.Id);
        return Redirect("/Blogs");
    }

    public async Task<IActionResult> OnPostAddUsers()
    {
        try
        {
            await _data.AddUser(newUsersModel.Name, newUsersModel.City, newUsersModel.State);
            return Redirect("/Blogs");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace uTestAndForms.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace uTestAndForms.Pages;

public class Index : PageModel
{
    public void OnGet()
    {

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace uTestAndForms.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/About/Index.cshtml
@page
@model Index

@{
    Layout = Layout;
}

<section>
    <h1>hello from about</h1>
</section>

Pages/Blogs/Index.cshtml
@page "{nameParam?}"
@model IndexForBlogs


@{
    Layout = Layout;

    var modalState = false;

}


<section class="table-wrapper">

    <div class="header-grid">
        <h1>
            SQL Example
        </h1>
        <div class="btn-flex">
            <button class="add-btn">Add</button>
            <button class="update-btn">update</button>
            <button class="search-btn">Search</button>
            <button class="dlt-btn"> Delete</button>
        </div>
    </div>


    <table class="table-wrapper">

        <tr>
            <ul class="list-one">
                <li class="delete">
                    <svg id="delete-toggle" xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 16 16">
                        <g fill="white">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/><path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                        </g>
                    </svg>

                    <div data-modal-body="false" id="delete-modal">
                        <div class="delete-flex">
                            <form asp-page-handler="DeleteUserWithId" method="POST">
                                <input
                                    placeholder="Enter ID"
                                    class="delete-input"
                                    asp-for="newUsersModel.Id" type="text">
                                <input
                                    class="delete-submit"
                                    value="Delete" type="submit"/>
                            </form>
                        </div>
                    </div>

                </li>

                <li class="add">
                    <svg id="add-toggle" xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 20 20">
                        <path fill="white" d="M11 9h4v2h-4v4H9v-4H5V9h4V5h2v4zm-1 11a10 10 0 1 1 0-20a10 10 0 0 1 0 20zm0-2a8 8 0 1 0 0-16a8 8 0 0 0 0 16z"/>
                    </svg>

                    <div data-modal-body="false" id="add-modal">
                        <div class="add-flex">
                            <form asp-page-handler="AddUsers" method="post">

                                <label asp-for="newUsersModel.Name">Name: </label>

                                <input type="text" asp-for="newUsersModel.Name">

                                <label asp-for="newUsersModel.City">City: </label>

                                <input type="text" asp-for="newUsersModel.City">

                                <label asp-for="newUsersModel.State">State: </label>

                                <input type="text" asp-for="newUsersModel.State">

                                <input class="user-submit" value="Add User" type="submit"/>

                            </form>
                        </div>
                    </div>
                </li>
                <li class="search">
                    <svg id="search-toggle" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5A6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5S14 7.01 14 9.5S11.99 14 9.5 14z"/>
                    </svg>

                    <div id="search-modal" data-modal-body="false">
                        <form METHOD="get">
                            <div class="form-flex">
                                <input
                                    placeholder="Enter Name Or Letter"
                                    class="search-input" asp-for="nameParam" type="search">
                                <input
                                    value="Search"
                                    class="search-submit" type="submit">
                            </div>
                        </form>
                    </div>

                </li>

                <li class="refresh">
                    <a asp-page-handler="Refresh">
                        <svg xmlns="http://www.w3l.org/2000/svg" width="33" height="33" viewBox="0 0 24 24">
                            <path fill="white" d="M17.65 6.35A7.958 7.958 0 0 0 12 4c-4.42 0-7.99 3.58-7.99 8s3.57 8 7.99 8c3.73 0 6.84-2.55 7.73-6h-2.08A5.99 5.99 0 0 1 12 18c-3.31 0-6-2.69-6-6s2.69-6 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z"/>
                        </svg>
                    </a>
                </li>
            </ul>
        </tr>

        <div class="tbody-grid">
            @foreach (var user in Model.newUsers)
            {
                <tbody>
                <tr>
                    <th>Name:</th>
                    <td>
                        @user.Name
                    </td>
                </tr>
                <tr>
                    <th>City:</th>
                    <td>
                        @user.City
                    </td>
                </tr>
                <tr>
                    <th>State:</th>
                    <td>
                        @user.State
                    </td>
                </tr>
                <tr>
                    <th>Id:</th>
                    <td>
                        @user.Id
                    </td>
                </tr>
                </tbody>
            }
        </div>


    </table>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title h2" id="exampleModalLongTitle">Delete User</h5>
                    <button type="button" class="myModalX btn btn-dark" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>


                <div class="modal-body">
                    <form class="d-flex gap-2 align-content-center" asp-page-handler="DeleteUserWithId" method="POST">
                        <input class="h-auto" placeholder="ID" asp-for="newUsersModel.Id" type="text">
                        <input class="btn btn-sm btn-danger" type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>


</section>


<style>
    .lob>td{
    color:purple;
    }
    .lob:hover{font-weight: bolder; transition: ease-in-out .2s;cursor: url("http://www.rw-designer.com/cursor-extern.php?id=5311"),auto}
</style>

@section Scripts{


    <script type="text/javascript">


function modalActivator(activatorElemID){
       return document.getElementById(activatorElemID);
   }

   function modalSelector(desiredModalId){
       return document.getElementById(desiredModalId);
   }

   function modalToggler(modalType){
       const modalState = modalType.getAttribute('data-modal-body');


      if(modalState === "false"){
                      modalType.setAttribute("data-modal-body","true");
                  } else {
                      modalType.setAttribute("data-modal-body","false");
        }
   }



   window.onclick = function (event){

        // Dear, whoever (Probably just me) feel free to add your modals here for automatic closing when clicking out of form or input fields.

        const myModals = ['search-modal','delete-modal','add-modal'];

        const allModals = [];

        for(let i = 0; i < myModals.length; i ++){
            allModals.push(modalSelector(myModals[i]))
        }


       allModals.map((i)=>{
           if(event.target == i){
               modalToggler(i)
           }
       })
   };

    modalActivator('search-toggle').addEventListener("click",()=>modalToggler(modalSelector('search-modal')))

    modalActivator('delete-toggle').addEventListener('click',()=>modalToggler(modalSelector('delete-modal')))

    modalActivator('add-toggle').addEventListener('click',()=>modalToggler(modalSelector('add-modal')))



</script>
}

Pages/Index.cshtml
@page
@model Index

@{
    Layout = Layout;
}


<div class="content-wrapper">

    <section class="index-section index-section-styles">
        <div class="header-text">

            <h1>
                Dylan Sm<span class="letter-i">i</span>th
            </h1>

            <p>
                Hi, I'ma a front and back end applications developer from <br/><span class="ok">Oklahoma</span>
            </p>

        </div>

    </section>

    <section class="work-section work-section-styles">
        <h2 >Work</h2>
        <p>
            I have worked with multiple locally owned companies in and around the Tulsa, OK areas. Below is the site of the last company I worked for. The site uses Svelte, Contentful, Tailwind CSS, and js Email for contacting the owners.
        </p>
        <a href="https://www.tulsaoverhead.com">Tulsa Overhead</a>

    </section>

    <section class="auto-banner auto-banner-styles">
        <ul class="animated">
            <li>TailwindCSS</li>
            <li>React</li>
            <li>C#</li>
            <li>ASP.NET Core</li>
            <li>Svelte</li>
            <li>Typescript</li>
            <li>SCSS</li>
            <li>SQL Server</li>
        </ul>
        <ul class="animated" aria-hidden="true">
            <li>TailwindCSS</li>
            <li>React</li>
            <li>C#</li>
            <li>ASP.NET Core</li>
            <li>Svelte</li>
            <li>Typescript</li>
            <li>SCSS</li>
            <li>SQL Server</li>
        </ul>
    </section>

    <section class="about-section about-section-styles">
        <h3 >About</h3>
        <p>
            I enjoy spending time with my dog and my girlfriend in my free time. I'm an easy going guy and am usually working on a project in either the front end using react or the back end using ASP.net.
        </p>
    </section>

</div>


<script type="text/javascript">
    const Animated = document.querySelector('.animated')
    const UL = document.querySelector('h2');

       Animated.onanimationiteration = ()=>{

        Animated.insertAdjacentHTML("afterend",Animated.outerHTML);
        Animated.nextElementSibling.setAttribute('aria-hidden','true');

        console.log("ended")

       };


</script>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>@ViewData["Title"] - uTestAndForms</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

    <link rel="stylesheet" href="~/uTestAndForms.styles.css" asp-append-version="true"/>

    <link rel="stylesheet" href="~/css/Layout/layout.css" asp-append-version="true"/>

    <link rel="stylesheet" href="~/css/Index/Index.css"/>

    <link rel="stylesheet" href="~/css/SqlTables/SqlStyles.css"/>


    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Megrim&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

</head>
<body>
<header>
    <div class="container navbar navbar-styles">

        <div class="nav-items nav-items-styles">
            <div>
                <a class="dylan-anchor" asp-page="/Index">Dylan</a>
            </div>
            <icon id="burger">
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <path d="M0 14H14V11.6667H0V14ZM0 8.16667H14V5.83333H0V8.16667ZM0 0V2.33333H14V0H0Z" fill="white"/>
                </svg>
            </icon>

            <div id="nav-menu" data-nav-state="false" class="navbar-menu navbar-menu-style">
                <ul>
                    <li>
                        <a asp-page="/Index">Home</a>
                    </li>
                    <li>
                        <a asp-page="/About/Index">About</a>
                    </li>
                    <li>
                        <a asp-page="/Blogs/Index">Blogs</a>
                    </li>
                    <li>three</li>
                    <li>four</li>
                </ul>
            </div>
        </div>

    </div>
</header>

<script src="~/js/site.js" asp-append-version="true"></script>

<partial name="_NavPartial"/>

<div class="section-wrapper index-container col-md-8 col-xxl-12 ">
    <main role="main" class="pb-3 ">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted">
    <div class="container">
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


@await RenderSectionAsync("Scripts", false)

</body>

<script type="text/javascript">
      const burger = document.getElementById("burger");
      const navMenu = document.getElementById("nav-menu")

      burger.addEventListener("click",function(){

          navMenu.getAttribute("data-nav-state") === "false" ? navMenu.setAttribute("data-nav-state","true"): navMenu.setAttribute("data-nav-state","false");


          console.log(navMenu.getAttribute("data-nav-state"))
      });


</script>

</html>

Pages/Shared/_NavPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/Layout/layoutPartial.css">
    <link rel="stylesheet" href="~/css/Layout/nav-button.css">
</head>


<header id="slider" data-slide="closed">


    <ul class="large-nav large-nav-styles">

        <li>
            <a asp-page="/Index">Home</a>
        </li>
        <li>
            <a asp-page="/About/Index">About</a>
        </li>
        <li>
            <a asp-page="/Blogs/Index">Blogs</a>
        </li>

    </ul>

    <div class="nav-menu nav-menu-styles">
        <ul>

            <li>
                <a class="dylan-anchor" asp-page="/Index">Dylan</a>
            </li>


            <li onclick="ActivateSlide()" id="burger">

                <div id="icon" class="Icon open">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

            </li>


            <span id="copy">
                &copy
            </span>


        </ul>
    </div>


</header>


<script type="text/javascript">

    const Slider = document.getElementById("slider");


    function ActivateSlide(){
      const State = Slider.getAttribute("data-slide");



      State === "closed" ? Slider.setAttribute("data-slide","open"):
      Slider.setAttribute("data-slide","closed");

      console.log(State)

    }

    const icon = document.getElementById("icon");

    icon.onclick = function() {
      if (this.className === "Icon open") {
        this.className = "Icon";
      } else {
        this.className = "Icon open";
      }
    };




</script>